### ISSUE TITLE
Windows Container intermittently ends up with no outbound network access after deployment

### ISSUE THREAD

**Issue by njwilloughby** [MicrosoftFeedback/aci-issues#11]
Hi,

I'm deploying multiple Windows Container Groups using an ARM template - normally around 10-20 container groups via single ARM template. Out of these 10-20 containers about 1-2 will end up with no outbound network access. Inbound network access on it's external IP is fine into the container but outbound fails.

The issue does not seem to rectify itself and the container will still be failing to connect to external http endpoints after an hour of being deployed.

I have also observed that most containers initially have no outbound network access but this normally resolves with a few minutes.

Please let me know if any additional details will help with this issue. 

Thanks

Nathan

**Comment by rbitia** [comment]
Thanks for the feedback! We are looking into the cause of this.

**Comment by seanmck** [comment]
We believe this is resolved now. Please reopen if you're still seeing it.
