### ISSUE TITLE
Limit of 20 Container Groups per Region in a Subscription

### ISSUE THREAD

**Issue by njwilloughby** [MicrosoftFeedback/aci-issues#12]
Hi,

What is the plan with the limit of container groups per region within a subscription?

At the moment it is set to 20 and cannot be increased (or support was unable to provide an increase).

Is this just a Preview hard limit? 

I'm looking to deploy up to 250 container (normally around 100 or so) for short bursts of time 30-60 mins.

Thanks

Nathan

**Comment by rbitia** [comment]
Hi Nathan, 

If you submit a support ticket through Azure we can look into raising the limit for you. Otherwise yes, that's the limit for right now but we have plans to increase it by GA. 

Thanks,
Ria

**Comment by seanmck** [comment]
As @rbitia, you can increase this limit through customer support, so closing.
