### ISSUE TITLE
ACI creation failed

### ISSUE THREAD

**Issue by ramamaram2** [MicrosoftFeedback/aci-issues#13]
hi ,

I have just created one instance by following below link as suggested by you. But container status in in failed state.

Link: https://azure.microsoft.com/en-in/blog/announcing-azure-container-instances/

I have used the following commands.
command1: az container  create --name helloworld --image seanmckenna/helloworld --ip-address public -g sample

command 2 : az container show --name helloworld -g sample -o table

Output : Name        ResourceGroup    ProvisioningState    Image                   IP:ports          CPU/Memory       OsType    Location
----------  ---------------  -------------------  ----------------------  ----------------  ---------------  --------  ----------
helloworld  sample           Failed               seanmckenna/helloworld  13.88.189.182:80  1.0 core/1.5 gb  Linux     westus

I could n't find any error message in logs ; 

Command 3 : az container logs --name helloworld -g sample
Log of container 'helloworld' in container group 'helloworld' is not available yet. Please check container 'InstanceView' for more information or retry later.

Even in GUI it does n't show any specific error messsage.

Can you please help me in debugging this issue.

Regards,
nagesh

**Comment by rbitia** [comment]
Hi - instead of seanmckenna/helloworld try microsoft/helloworld.
Here's the full command: 
az container create --name mycontainer --image microsoft/aci-helloworld --resource-group myResourceGroup --ip-address public

Thanks!
