### ISSUE TITLE
Example in `az container create -h` uses incorrect `registry-login-server` parameter

### ISSUE THREAD

**Issue by joshualyon** [MicrosoftFeedback/aci-issues#5]
When issuing a call to `az container create -h`, the first Image Registry argument is listed as `--registry-login-server`, but the last example uses `--registry-server`.

I tested the `--registry-server` argument to see if it was an alias for the correct argument, but it yielded the error message:
```
az: error: unrecognized arguments: --registry-server test.com
```

**Comment by seanmck** [comment]
https://github.com/Azure/azure-cli/pull/4208

**Comment by seanmck** [comment]
Fixed.
